### ISSUE TITLE
Support of multi-modules projects

### ISSUE THREAD

**Issue by vrnsky** [Bonajo/pitest-report-action#14]
### Problem
In a multi-module project such as [Java A to Z](https://github.com/vrnsky/java-a-to-z), I have modules that can contain inner modules.

Both modules have their unit tests. The GitHub Actions performed mutation testing for each module. Publication checks occur only for the outer model, not the inner one.

### Description
I don't know the best approach yet. But, action should perform a recursive search for mutation.xml in the target folders of multimodule projects.

**Comment by Bonajo** [comment]
Should be fixed in latest version (`v0.8`).

Please make another issue if you run into further problems.
